### ISSUE TITLE
Erreur sur la liste des blogs intéressants

### ISSUE THREAD

**Issue by Pilooz** [laclasse-com/service-blogs#20]
Si la liste est vide, une erreur est tracée dans les logs.
----------------------------------------------------------------------------------
```
D, [2016-01-27T13:51:26.229737 #66655] DEBUG -- : Call to API WordPress with action get with url 'http://blogs.dev.laclasse.com/wp-login.php?ENT_action=USER_BLOG_LIST' took 0.055306 s
D, [2016-01-27T13:51:26.229957 #66655] DEBUG -- : "[]"
D, [2016-01-27T13:51:26.230019 #66655] DEBUG -- : "[]"
E, [2016-01-27T13:51:26.231227 #66655] ERROR -- : undefined method `sample' for #<Hash:0x007fadd9224c30> (NoMethodError)
/Users/pgl/developpement/service-blogs/lib/blogs.rb:298:in `block in sample_to_interest_of'
/Users/pgl/developpement/service-blogs/lib/blogs.rb:294:in `collect!'
/Users/pgl/developpement/service-blogs/lib/blogs.rb:294:in `sample_to_interest_of'
/Users/pgl/developpement/service-blogs/lib/blogs.rb:56:in `interest'
/Users/pgl/developpement/service-blogs/api/blogs.rb:28:in `block in <class:BlogsApi>'
/usr/local/lib/ruby/gems/2.2.0/gems/grape-0.14.0/lib/grape/endpoint.rb:67:in `call'
/usr/local/lib/ruby/gems/2.2.0/gems/grape-0.14.0/lib/grape/endpoint.rb:67:in `block (2 levels) in generate_api_method'
/usr/local/lib/ruby/gems/2.2.0/gems/activesupport-4.2.5.1/lib/active_support/notifications.rb:166:in `instrument'
/usr/local/lib/ruby/gems/2.2.0/gems/grape-0.14.0/lib/grape/endpoint.rb:66:in `block in generate_api_method'
/usr/local/lib/ruby/gems/2.2.0/gems/grape-0.14.0/lib/grape/endpoint.rb:263:in `call'
/usr/local/lib/ruby/gems/2.2.0/gems/grape-0.14.0/lib/grape/endpoint.rb:263:in `block in run'
/usr/local/lib/ruby/gems/2.2.0/gems/activesupport-4.2.5.1/lib/active_support/notifications.rb:166:in `instrument'
/usr/local/lib/ruby/gems/2.2.0/gems/grape-0.14.0/lib/grape/endpoint.rb:231:in `run'
/usr/local/lib/ruby/gems/2.2.0/gems/grape-0.14.0/lib/grape/endpoint.rb:314:in `block in build_stack'
/usr/local/lib/ruby/gems/2.2.0/gems/grape-0.14.0/lib/grape/middleware/base.rb:25:in `call'
/usr/local/lib/ruby/gems/2.2.0/gems/grape-0.14.0/lib/grape/middleware/base.rb:25:in `call!'
/usr/local/lib/ruby/gems/2.2.0/gems/grape-0.14.0/lib/grape/middleware/base.rb:19:in `call'
/usr/local/lib/ruby/gems/2.2.0/gems/grape-0.14.0/lib/grape/middleware/error.rb:27:in `block in call!'
/usr/local/lib/ruby/gems/2.2.0/gems/grape-0.14.0/lib/grape/middleware/error.rb:26:in `catch'
/usr/local/lib/ruby/gems/2.2.0/gems/grape-0.14.0/lib/grape/middleware/error.rb:26:in `call!'
/usr/local/lib/ruby/gems/2.2.0/gems/grape-0.14.0/lib/grape/middleware/base.rb:19:in `call'
/usr/local/lib/ruby/gems/2.2.0/gems/rack-1.6.4/lib/rack/head.rb:13:in `call'
/usr/local/lib/ruby/gems/2.2.0/gems/grape-0.14.0/lib/grape/endpoint.rb:215:in `call!'
/usr/local/lib/ruby/gems/2.2.0/gems/grape-0.14.0/lib/grape/endpoint.rb:209:in `call'
/usr/local/lib/ruby/gems/2.2.0/gems/rack-mount-0.8.3/lib/rack/mount/route_set.rb:152:in `block in call'
/usr/local/lib/ruby/gems/2.2.0/gems/rack-mount-0.8.3/lib/rack/mount/code_generation.rb:96:in `block in recognize'
/usr/local/lib/ruby/gems/2.2.0/gems/rack-mount-0.8.3/lib/rack/mount/code_generation.rb:75:in `optimized_each'
/usr/local/lib/ruby/gems/2.2.0/gems/rack-mount-0.8.3/lib/rack/mount/code_generation.rb:95:in `recognize'
/usr/local/lib/ruby/gems/2.2.0/gems/rack-mount-0.8.3/lib/rack/mount/route_set.rb:141:in `call'
/usr/local/lib/ruby/gems/2.2.0/gems/grape-0.14.0/lib/grape/api.rb:114:in `call'
/usr/local/lib/ruby/gems/2.2.0/gems/grape-0.14.0/lib/grape/api.rb:44:in `call!'
/usr/local/lib/ruby/gems/2.2.0/gems/grape-0.14.0/lib/grape/api.rb:39:in `call'
/usr/local/lib/ruby/gems/2.2.0/gems/rack-1.6.4/lib/rack/urlmap.rb:66:in `block in call'
/usr/local/lib/ruby/gems/2.2.0/gems/rack-1.6.4/lib/rack/urlmap.rb:50:in `each'
/usr/local/lib/ruby/gems/2.2.0/gems/rack-1.6.4/lib/rack/urlmap.rb:50:in `call'
/usr/local/lib/ruby/gems/2.2.0/gems/omniauth-1.2.2/lib/omniauth/strategy.rb:186:in `call!'
/usr/local/lib/ruby/gems/2.2.0/gems/omniauth-1.2.2/lib/omniauth/strategy.rb:164:in `call'
/usr/local/lib/ruby/gems/2.2.0/gems/omniauth-1.2.2/lib/omniauth/builder.rb:59:in `call'
/usr/local/lib/ruby/gems/2.2.0/bundler/gems/laclasse-common-859b875e3593/laclasse/helpers/rack.rb:14:in `call'
/usr/local/lib/ruby/gems/2.2.0/gems/rack-1.6.4/lib/rack/session/abstract/id.rb:225:in `context'
/usr/local/lib/ruby/gems/2.2.0/gems/rack-1.6.4/lib/rack/session/abstract/id.rb:220:in `call'
/usr/local/lib/ruby/gems/2.2.0/gems/rack-rewrite-1.5.1/lib/rack/rewrite.rb:24:in `call'
/usr/local/lib/ruby/gems/2.2.0/gems/rack-1.6.4/lib/rack/tempfile_reaper.rb:15:in `call'
/usr/local/lib/ruby/gems/2.2.0/gems/rack-1.6.4/lib/rack/lint.rb:49:in `_call'
/usr/local/lib/ruby/gems/2.2.0/gems/rack-1.6.4/lib/rack/lint.rb:37:in `call'
/usr/local/lib/ruby/gems/2.2.0/gems/rack-1.6.4/lib/rack/showexceptions.rb:24:in `call'
/usr/local/lib/ruby/gems/2.2.0/gems/rack-1.6.4/lib/rack/commonlogger.rb:33:in `call'
/usr/local/lib/ruby/gems/2.2.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:219:in `call'
/usr/local/lib/ruby/gems/2.2.0/gems/rack-1.6.4/lib/rack/chunked.rb:54:in `call'
/usr/local/lib/ruby/gems/2.2.0/gems/rack-1.6.4/lib/rack/content_length.rb:15:in `call'
/usr/local/lib/ruby/gems/2.2.0/gems/puma-2.15.3/lib/puma/server.rb:541:in `handle_request'
/usr/local/lib/ruby/gems/2.2.0/gems/puma-2.15.3/lib/puma/server.rb:388:in `process_client'
/usr/local/lib/ruby/gems/2.2.0/gems/puma-2.15.3/lib/puma/server.rb:270:in `block in run'
/usr/local/lib/ruby/gems/2.2.0/gems/puma-2.15.3/lib/puma/thread_pool.rb:106:in `call'
/usr/local/lib/ruby/gems/2.2.0/gems/puma-2.15.3/lib/puma/thread_pool.rb:106:in `block in spawn_thread'
```

**Comment by hquenin** [comment]
car l'api WP ne renvoie pas du JSON..

**Comment by Pilooz** [comment]
Pourtant si ?
L'entête renvoie content-type : application/json. Vérifie le dans ton firebug pour voir si on a bien pareil.
(serveur : blogs.dev.laclasse.com)
En fait le retour est un  tableau vide, cas qui ne semble pas être gérer dans le code ? A vérifier.

Il semble que l'url que tu envoies n'est pas la bonne.
- pour la liste des blogs de l'utilisateur 
http://blogs.dev.laclasse.com/wp-login.php?ENT_action=USER_BLOG_LIST@username=[login de l'utilisateur]
- Pour la liste de tous les blogs de la plateforme, dont doivent s'inspirer les préconisations d'abonnement, http://blogs.dev.laclasse.com/wp-login.php?ENT_action=BLOG_LIST

**Comment by hquenin** [comment]
Autant pour moi une fonction que je n'ai pas corrigé suite à des modification..J'en ai pour 3 seconde pour corriger ^^

**Comment by Pilooz** [comment]
:+1:
