### ISSUE TITLE
Le rattachement à un blog ne se fait pas.

### ISSUE THREAD

**Issue by Pilooz** [laclasse-com/service-blogs#25]
Lorsque l'on appuie sur la coche verte d'une case, un GET de souscription au blog est lancé côté serveur. 
Celle-ci débouche sur une erreur : 
```
"http://blogs.dev.laclasse.com/wp-login.php?blogname=actualitestheatre&blogtype=ENV&debug=N&ent=laclasseV3"
E, [2016-05-09T16:02:19.647230 #7006] ERROR -- : 757: unexpected token at '<html><head><title>CAS Authentication wanted!</title></head><body><h1>CAS Authentication wanted!</h1><p>You should already have been redirected to the CAS server. Click <a href="https://v3dev.laclasse.com/sso/login?service=http%3A%2F%2Fblogs.dev.laclasse.com%2Fwp-login.php%3Fblogname%3Dactualitestheatre%26blogtype%3DENV%26debug%3DN%26ent%3DlaclasseV3">here</a> to continue.</p><hr><address>phpCAS 1.2.0 using server <a href="https://v3dev.laclasse.com/sso/">https://v3dev.laclasse.com/sso/</a> (CAS 2.0)</a></address></body></html>'====> ["/usr/local/lib/ruby/gems/2.2.0/gems/json-1.8.3/lib/json/common.rb:155:in `parse'", 
	 "/usr/local/lib/ruby/gems/2.2.0/gems/json-1.8.3/lib/json/common.rb:155:in `parse'", 
	 "/Users/pgl/developpement/service-blogs/lib/wordpress.rb:71:in `manage_response'", 
	 "/Users/pgl/developpement/service-blogs/lib/wordpress.rb:19:in `block in send_request'", 
	 "/usr/local/lib/ruby/gems/2.2.0/gems/rest-client-1.8.0/lib/restclient/request.rb:493:in `call'", 
	 "/usr/local/lib/ruby/gems/2.2.0/gems/rest-client-1.8.0/lib/restclient/request.rb:493:in `process_result'", 
	 "/usr/local/lib/ruby/gems/2.2.0/gems/rest-client-1.8.0/lib/restclient/request.rb:421:in `block in transmit'", 
	 "/usr/local/Cellar/ruby/2.2.1/lib/ruby/2.2.0/net/http.rb:853:in `start'", 
	 "/usr/local/lib/ruby/gems/2.2.0/gems/rest-client-1.8.0/lib/restclient/request.rb:413:in `transmit'", 
	 "/usr/local/lib/ruby/gems/2.2.0/gems/rest-client-1.8.0/lib/restclient/request.rb:176:in `execute'", 
	 "/usr/local/lib/ruby/gems/2.2.0/gems/rest-client-1.8.0/lib/restclient/request.rb:41:in `execute'", 
	 "/usr/local/lib/ruby/gems/2.2.0/gems/rest-client-1.8.0/lib/restclient.rb:65:in `get'", 
	 "/Users/pgl/developpement/service-blogs/lib/wordpress.rb:16:in `send_request'", 
	 "/Users/pgl/developpement/service-blogs/lib/blogs.rb:193:in `subcribe'", 
	 "/Users/pgl/developpement/service-blogs/lib/blogs.rb:71:in `execute_action'", 
	 "/Users/pgl/developpement/service-blogs/lib/blogs.rb:20:in `block in save'", 
	 "/Users/pgl/developpement/service-blogs/lib/blogs.rb:17:in `each'", 
	 "/Users/pgl/developpement/service-blogs/lib/blogs.rb:17:in `save'", 
	 "/Users/pgl/developpement/service-blogs/api/blogs.rb:54:in `block in <class:BlogsApi>'", 
	 "/usr/local/lib/ruby/gems/2.2.0/gems/grape-0.14.0/lib/grape/endpoint.rb:67:in `call'", 
	 "/usr/local/lib/ruby/gems/2.2.0/gems/grape-0.14.0/lib/grape/endpoint.rb:67:in `block (2 levels) in generate_api_method'", 
	 "/usr/local/lib/ruby/gems/2.2.0/gems/activesupport-4.2.6/lib/active_support/notifications.rb:166:in `instrument'", 
	 "/usr/local/lib/ruby/gems/2.2.0/gems/grape-0.14.0/lib/grape/endpoint.rb:66:in `block in generate_api_method'", 
	 "/usr/local/lib/ruby/gems/2.2.0/gems/grape-0.14.0/lib/grape/endpoint.rb:263:in `call'", 
	 "/usr/local/lib/ruby/gems/2.2.0/gems/grape-0.14.0/lib/grape/endpoint.rb:263:in `block in run'", 
	 "/usr/local/lib/ruby/gems/2.2.0/gems/activesupport-4.2.6/lib/active_support/notifications.rb:166:in `instrument'", 
	 "/usr/local/lib/ruby/gems/2.2.0/gems/grape-0.14.0/lib/grape/endpoint.rb:231:in `run'", 
	 "/usr/local/lib/ruby/gems/2.2.0/gems/grape-0.14.0/lib/grape/endpoint.rb:314:in `block in build_stack'", 
	 "/usr/local/lib/ruby/gems/2.2.0/gems/grape-0.14.0/lib/grape/middleware/base.rb:25:in `call'", 
	 "/usr/local/lib/ruby/gems/2.2.0/gems/grape-0.14.0/lib/grape/middleware/base.rb:25:in `call!'", 
	 "/usr/local/lib/ruby/gems/2.2.0/gems/grape-0.14.0/lib/grape/middleware/base.rb:19:in `call'", 
	 "/usr/local/lib/ruby/gems/2.2.0/gems/grape-0.14.0/lib/grape/middleware/error.rb:27:in `block in call!'", 
	 "/usr/local/lib/ruby/gems/2.2.0/gems/grape-0.14.0/lib/grape/middleware/error.rb:26:in `catch'", 
	 "/usr/local/lib/ruby/gems/2.2.0/gems/grape-0.14.0/lib/grape/middleware/error.rb:26:in `call!'", 
	 "/usr/local/lib/ruby/gems/2.2.0/gems/grape-0.14.0/lib/grape/middleware/base.rb:19:in `call'", 
	 "/usr/local/lib/ruby/gems/2.2.0/gems/rack-1.6.4/lib/rack/head.rb:13:in `call'", 
	 "/usr/local/lib/ruby/gems/2.2.0/gems/grape-0.14.0/lib/grape/endpoint.rb:215:in `call!'", 
	 "/usr/local/lib/ruby/gems/2.2.0/gems/grape-0.14.0/lib/grape/endpoint.rb:209:in `call'", 
	 "/usr/local/lib/ruby/gems/2.2.0/gems/rack-mount-0.8.3/lib/rack/mount/route_set.rb:152:in `block in call'", 
	 "/usr/local/lib/ruby/gems/2.2.0/gems/rack-mount-0.8.3/lib/rack/mount/code_generation.rb:96:in `block in recognize'", 
	 "/usr/local/lib/ruby/gems/2.2.0/gems/rack-mount-0.8.3/lib/rack/mount/code_generation.rb:68:in `optimized_each'", 
	 "/usr/local/lib/ruby/gems/2.2.0/gems/rack-mount-0.8.3/lib/rack/mount/code_generation.rb:95:in `recognize'", 
	 "/usr/local/lib/ruby/gems/2.2.0/gems/rack-mount-0.8.3/lib/rack/mount/route_set.rb:141:in `call'", 
	 "/usr/local/lib/ruby/gems/2.2.0/gems/grape-0.14.0/lib/grape/api.rb:114:in `call'", 
	 "/usr/local/lib/ruby/gems/2.2.0/gems/grape-0.14.0/lib/grape/api.rb:44:in `call!'", 
	 "/usr/local/lib/ruby/gems/2.2.0/gems/grape-0.14.0/lib/grape/api.rb:39:in `call'", 
	 "/usr/local/lib/ruby/gems/2.2.0/gems/rack-1.6.4/lib/rack/urlmap.rb:66:in `block in call'", 
	 "/usr/local/lib/ruby/gems/2.2.0/gems/rack-1.6.4/lib/rack/urlmap.rb:50:in `each'", 
	 "/usr/local/lib/ruby/gems/2.2.0/gems/rack-1.6.4/lib/rack/urlmap.rb:50:in `call'", 
	 "/usr/local/lib/ruby/gems/2.2.0/gems/omniauth-1.2.2/lib/omniauth/strategy.rb:186:in `call!'", 
	 "/usr/local/lib/ruby/gems/2.2.0/gems/omniauth-1.2.2/lib/omniauth/strategy.rb:164:in `call'", 
	 "/usr/local/lib/ruby/gems/2.2.0/gems/omniauth-1.2.2/lib/omniauth/builder.rb:59:in `call'", 
	 "/usr/local/lib/ruby/gems/2.2.0/bundler/gems/laclasse-common-472789cfcf3f/laclasse/helpers/rack.rb:14:in `call'", 
	 "/usr/local/lib/ruby/gems/2.2.0/gems/rack-1.6.4/lib/rack/session/abstract/id.rb:225:in `context'", 
	 "/usr/local/lib/ruby/gems/2.2.0/gems/rack-1.6.4/lib/rack/session/abstract/id.rb:220:in `call'", 
	 "/usr/local/lib/ruby/gems/2.2.0/gems/rack-rewrite-1.5.1/lib/rack/rewrite.rb:24:in `call'", 
	 "/usr/local/lib/ruby/gems/2.2.0/gems/rack-1.6.4/lib/rack/tempfile_reaper.rb:15:in `call'", 
	 "/usr/local/lib/ruby/gems/2.2.0/gems/rack-1.6.4/lib/rack/lint.rb:49:in `_call'", 
	 "/usr/local/lib/ruby/gems/2.2.0/gems/rack-1.6.4/lib/rack/lint.rb:37:in `call'", 
	 "/usr/local/lib/ruby/gems/2.2.0/gems/rack-1.6.4/lib/rack/showexceptions.rb:24:in `call'", 
	 "/usr/local/lib/ruby/gems/2.2.0/gems/rack-1.6.4/lib/rack/commonlogger.rb:33:in `call'", 
	 "/usr/local/lib/ruby/gems/2.2.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:219:in `call'", 
	 "/usr/local/lib/ruby/gems/2.2.0/gems/rack-1.6.4/lib/rack/chunked.rb:54:in `call'", 
	 "/usr/local/lib/ruby/gems/2.2.0/gems/rack-1.6.4/lib/rack/content_length.rb:15:in `call'", 
	 "/usr/local/lib/ruby/gems/2.2.0/gems/puma-3.4.0/lib/puma/configuration.rb:224:in `call'", 
	 "/usr/local/lib/ruby/gems/2.2.0/gems/puma-3.4.0/lib/puma/server.rb:569:in `handle_request'", 
	 "/usr/local/lib/ruby/gems/2.2.0/gems/puma-3.4.0/lib/puma/server.rb:406:in `process_client'", 
	 "/usr/local/lib/ruby/gems/2.2.0/gems/puma-3.4.0/lib/puma/server.rb:271:in `block in run'", 
	 "/usr/local/lib/ruby/gems/2.2.0/gems/puma-3.4.0/lib/puma/thread_pool.rb:114:in `call'", 
	 "/usr/local/lib/ruby/gems/2.2.0/gems/puma-3.4.0/lib/puma/thread_pool.rb:114:in `block in spawn_thread'"]
```

**Comment by Pilooz** [comment]
Il y a aussi une histoire de cross-origin dlorqu'on envoie une iFrame depuis le navigateur vers le serveur de blogs.
```
Blocage d'une requête multi-origines (Cross-Origin Request) : la politique « Same Origin » ne permet pas de consulter la ressource distante située sur https://blogs.dev.laclasse.com/wp-login.php?ent=laclasseV3. Raison : l'en-tête CORS « Access-Control-Allow-Origin » est manquant.
```

**Comment by Pilooz** [comment]
- [ ] bypasser l'authentification sur les apis de WP concernées
- [ ] protéger les apis concernées par une signature (la même que dans le reste de laclasse.com).
